language: rust
os:
  - linux
  - osx
  - windows
script:
  - cargo build --verbose --workspace
  - cargo test --verbose --workspace

jobs:
  include:
  - stage: Github Release
    deploy:
      provider: releases
      api_key: GITHUB_TOKEN=<token>
      file: "./target/release/wingman"
      cleanup: true
      on:
        tags: true
