language: rust
os:
  - linux
  - osx
  - windows
script:
  - cargo build --verbose --workspace
  - cargo test --verbose --workspace

deploy:
  provider: releases
  api_key: GITHUB_TOKEN=<travisOauth>
  file: "./target/release/wingman"
  cleanup: true
  on:
    tags: true