language: rust
os:
  - linux
  - osx
  - windows
script:
  - cargo build --verbose --workspace
  - cargo test --verbose --workspace

deploy:
  provider: releases
  api_key: token
  file: "./target/release/wingman"
  skip_cleanup: true
  on:
    tags: true